spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/javapolis
    username: postgres
    password: password
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    open-in-view: false
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
server:
  port: 8080
logging:
  level:
    root: INFO
    org.springframework.security: WARN
    org.springframework.mail: DEBUG

  mail:
    host: smtp.gmail.com
    port: 587
    username: your-email@gmail.com  # Замените на ваш email
    password: your-app-password      # Замените на пароль приложения Gmail
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    test-connection: false

# Базовый URL приложения
app:
  base-url: http://localhost:8080
