spring.application.name=factory-player
server.address=127.0.0.1
server.port=8081
spring.jackson.serialization.indent-output=false
factory.mode=@factory.mode@
server.error.include-message=always
spring.web.resources.cache.cachecontrol.no-store=true
